apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-devops.fullname" . }}-reconcile
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-devops.labels" . | nindent 4 }}
    app.kubernetes.io/component: reconcile
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kube-devops.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: reconcile
  template:
    metadata:
      labels:
        {{- include "kube-devops.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: reconcile
    spec:
      serviceAccountName: {{ include "kube-devops.fullname" . }}
      containers:
        - name: {{ include "kube-devops.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "reconcile"
          ports:
            - containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9090
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
