{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kube-devops.fullname" . }}-reconcile
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-devops.labels" . | nindent 4 }}
    app.kubernetes.io/component: reconcile
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "kube-devops.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: reconcile
{{- end }}
