apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-devops.fullname" . }}-watch
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-devops.labels" . | nindent 4 }}
    app.kubernetes.io/component: watch
spec:
  selector:
    {{- include "kube-devops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: watch
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
