apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-devops.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-devops.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  selector:
    {{- include "kube-devops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
  ports:
    - name: metrics
      port: 8443
      targetPort: 8443
      protocol: TCP
