apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-devops.fullname" . }}-reconcile
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-devops.labels" . | nindent 4 }}
    app.kubernetes.io/component: reconcile
spec:
  selector:
    {{- include "kube-devops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: reconcile
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
