{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kube-devops.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-devops.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
    release: stable
spec:
  selector:
    matchLabels:
      {{- include "kube-devops.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: webhook
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
{{- end }}
